---
# tasks file for roles/server-updates

- name: Check failed services
  shell:
    cmd: systemctl --failed
  become: yes
  register: result_sysctl_failed
  changed_when: false

- name: Display services failed
  debug:
    msg: "les services en erreurs: {{ result_sysctl_failed.stdout }}"

- name: Update packages list
  ansible.builtin.apt:
    update_cache: true
  become: yes
  register: result_apt_update
  when: result_sysctl_failed.failed == false

- name: Hold mysql packages
  shell:
    cmd: apt-mark hold mysql*
  become: yes
  register: result_hold_mysql
  changed_when: false
  when: result_apt_update.failed == false

- name: Hold php8 packages
  shell:
    cmd: apt-mark hold php8*
  become: yes
  register: result_hold_php8
  changed_when: false
  when: result_hold_mysql.failed == false

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: full
  become: yes
  register: result_apt_full_upgrade
  when: result_apt_update.failed == false

- name: result of the upgrade
  debug:
    msg: "This is the result of the upgraded packages: {{ result_apt_full_upgrade.msg }}"

- name: clean unused packaged
  ansible.builtin.apt:
    autoremove: true
  become: yes
  register: result_apt_autoremove
  when: result_apt_full_upgrade.failed == false

- name: Unhold mysql packages
  shell:
    cmd: apt-mark unhold mysql*
  become: yes
  register: result_unhold_mysql
  changed_when: false
  when: result_apt_autoremove.failed == false

- name: Unhold php8 packages
  shell:
    cmd: apt-mark unhold php8*
  become: yes
  register: result_unhold_php8
  changed_when: false
  when: result_unhold_mysql.failed == false

- name: result of the upgrade
  debug:
    msg: "This is the result of the unused packages cleaning: {{ result_apt_autoremove.stdout }}"
