---
# tasks file for roles/server-updates

- name: Check failed services
  shell:
    cmd: systemctl --failed
  register: result_sysctl_failed

- name: Display services failed
  debug:
    msg: "les services en erreurs: {{ result_sysctl_failed.stdout }}"

- name: Update packages list
  ansible.builtin.apt:
    update_cache: true
  register: result_apt_update
  when: result_sysctl_failed.failed == false

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: full
  register: result_apt_full_upgrade
  when: result_apt_update.failed == false

- name: result of the upgrade
  debug:
    msg: "This is the result of the upgraded packages: {{ result_apt_full_upgrade.msg }}"

- name: clean unused packaged
  ansible.builtin.apt:
    autoremove: true
  register: result_apt_autoremove
  when: result_apt_update.failed == false

- name: result of the upgrade
  debug:
    msg: "This is the result of the unused packages cleaning: {{ result_apt_autoremove.stdout }}"
